# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.
# yaml-language-server: $schema=./meta-schema.yaml

title: OCI Kubernetes Monitoring Solution
description: "OCI Kubernetes Monitoring Solution is a turn-key Kubernetes monitoring and management package based on the following OCI services: Logging Analytics, Monitoring, and Management Agent."
informationalText: "OCI Kubernetes Monitoring Solution is a turn-key Kubernetes monitoring and management package based on the following OCI services: Logging Analytics, Monitoring, and Management Agent."
schemaVersion: 1.1.0
version: "20221004"

# URL of Logo Icon used on Application Information tab. Logo must be 130x130 pixels.
# (Optional)
#logoUrl: https://cloudmarketplace.oracle.com/marketplace/content?contentId=53066708

source:
  type: marketplace  # enum - marketplace, quickstart or web

locale: "en"

variableGroups:
  - title: "hidden inputs"
    variables:
      - tenancy_ocid
      - region
      - user_ocid
      - private_key_path
      - fingerprint
      - boat_auth
      - boat_tenancy_ocid
      - compartment_ocid
      - current_user_ocid
    visible: false

  # These inputs are hidden from RMS UI and will be removed in future versions
  - title: "Depreciated inputs"
    variables:
      - oke_cluster_name
      - opt_create_dynamicGroup_and_policies
      - kubernetes_namespace
    visible: false

  - title: Select an OKE cluster deployed in this region to start monitoring
    variables:
      - oke_compartment_ocid
      - oke_cluster_ocid
      - oke_is_private
      - oke_subnet_or_pe_ocid
      - show_advanced_options

  - title: Create Dynamic Group and Policy (admin access required)
    variables:
      - dropdown_create_dynamicGroup_and_policies

  - title: "OCI Observability and Management Services Configuration"
    variables:
    - oci_onm_compartment_ocid
    - opt_create_new_la_logGroup
    - oci_la_logGroup_id
    - oci_la_logGroup_name
    - opt_import_dashboards
    - opt_create_new_la_entity
    - oke_cluster_entity_ocid

  - title: Helm Chart Configuration (Optional)
    variables:
      - stack_deployment_option
      - opt_skip_helm_chart
      - opt_deploy_metric_server
      - helm_chart_version
      - fluentd_baseDir_path
    visible: show_advanced_options

  - title: " " # intentionally empty
    variables:
      - tags

variables:

  ####
  ##  OKE Cluster Information
  ####

  # OKE Cluster Compartment
  oke_compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: "Select OKE cluster compartment"
    default: compartment_ocid

  # OKE Cluster OCID
  oke_cluster_ocid:
    type: oci:container:cluster:id
    dependsOn:
      compartmentId: ${oke_compartment_ocid}
    title: Select OKE cluster
    required: true

  # Option to enable/disable metric server installation during helm deployment
  oke_is_private:
    type: boolean
    title: Is the selected OKE cluster private?
    default: false
    # visible:
    #   eq:
    #     - ${stack_deployment_option}
    #     - "Full"

  # OKE Cluster OCID
  oke_subnet_or_pe_ocid:
    type: string
    title: "Enter OKE Node Subnet OCID or RMS Private Endpoint OCID"
    description: |-
      [★] This Subnet's Security List should allow Egress connection to OKE Cluster's API endpoint; Typically this is the oke-nodesubnet and NOT the oke-k8sApiEndpoint-subnet.
      [★] Note: If Subnet OCID is provided, a RMS Private Endpoint resource will be created.
      Alternatively, Users can provide OCID of an existing <a href="https://docs.oracle.com/en-us/iaas/Content/ResourceManager/Tasks/private-endpoints.htm" target="_blank" rel="noopener noreferrer">RMS Private Endpoint</a> as well.
    required: true
    pattern: "^ocid1\\.(subnet|ormprivateendpoint)\\.\\S+$"
    # maxLength: 93 # Don't set as realm ID is part of OCID
    minLength: 81 # mz char count in private endpoint ocid
    visible:
      and:
      - ${oke_is_private}
      # - eq:
      #   - ${stack_deployment_option}
      #   - "Full"

  # @Depreciated 
  # # Option to create Dynamic Group and Policies
  # opt_create_dynamicGroup_and_policies:
  #   type: boolean
  #   title: Select this check box to create OCI IAM dynamic group and policies which are required for the monitoring solution
  #   #description: "Ref: https://github.com/oracle-quickstart/oci-kubernetes-monitoring#pre-requisites"
  #   description: "Note: If node pools and the OKE cluster are in different compartments, then the dynamic group definition must be updated."
  #   default: false
  #   required: true

  # Option to create Dynamic Group and Policies
  dropdown_create_dynamicGroup_and_policies:
    type: enum
    title: " "
    # title: "Choose if required IAM resources should be created as part of the stack" # Choose option to create OCI IAM dynamic group and policies which are required for the monitoring solution
    #description: "Ref: https://github.com/oracle-quickstart/oci-kubernetes-monitoring#pre-requisites"
    description: |-
      [★] Dynamic Group and Policy must be created BEFORE executing this stack.
      [★] Reference: <a href="https://github.com/oracle-quickstart/oci-kubernetes-monitoring#pre-requisites" target="_blank" rel="noopener noreferrer">https://github.com/oracle-quickstart/oci-kubernetes-monitoring#pre-requisites</a>.
      [★] If node pools and the OKE cluster are in different compartments, you will need to create these resources manually or edit the created Dynamic Group.
    #   (DynamicGroup created via the stack will need to be updated in this case).
    #   [★] Users typically opt-out when:
    #   [1] User does not have access to create policy in root compartment.
    #   [2] If node pools and the OKE cluster are in different compartments
    #   (DynamicGroup created via the stack will need to be updated in this case).
    # [3] User wants to manage required policies outside of stack as part of an existing policy.
    enum:
    - "Create required IAM resources as part of the stack" # Setting enum as "True" fails to save input via stack UI
    - "I have already created Pre-requisites IAM resources"
    default: "" # Setting this value to "", forces user to select from one of the dropdown options
    required: true

  #  Stack Deployment Options
  stack_deployment_option:
    title: Choose deployment option
    description: |-
      [★] "Full" option deploys helm chart as well as creates OCI resources.
      [★] "Only OCI Resources" option creates only OCI resources. 
      [★] Note: You can find the <a href="https://helm.sh/docs/intro/using_helm/" target="_blank" rel="noopener noreferrer">helm cli</a> 
      commands in stack output to install & manage the helm chart outside of this stack.
# [★] Both options create following OCI resources: OCI LA Entity, OCI LA LogGroup, Management Agent Key, 
# RMS Private Endpoint, Management Dashboards, Policies and DynamicGroup.
# [★] "Full" option also deploys the <a href="https://oracle-quickstart.github.io/oci-kubernetes-monitoring" 
# target="_blank" rel="noopener noreferrer">helm chart</a>.
# [★] "Only OCI Resources" option does NOT deploy the helm chart.
# [★] Users typically opt to not install helm chart when they want to integrate the solution (helm chart) as part of 
# their existing kubernetes deployment stack.
# [★] If you opt for "Only OCI Resources" option, the stack will produce the required helm commands to install 
# the solution manually. (as outputs)
# [★] These commands will need to be executed from a node where K8s cluster is accessible.
    type: enum
    enum: # Dev Note - # Any change in following options must be refactored across schema.yaml
    - "Full"
    - "Only OCI Resources"
    required: true
    default: "Full"

  # Option to enable/disable metric server installation during helm deployment
  show_advanced_options:
    type: boolean
    title: Show Default/Optional Configuration?
    description: |-
      [★] Helm Chart
      [★] Logging Analytics Entity
      [★] Kubernetes Dashboard
    default: false

  ####
  ##  OCI Observability and Management Services Configuration
  ####

  # Compartment for creating OCI Observability and Management resources
  oci_onm_compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Select compartment for Logging Analytics, Management Agent, and Monitoring service resources
    description: |-
      This compartment will be used for creating dashboards, log groups, entities, 
      Management Agent keys, metric namespaces, and related resources. For a full list 
      of resources, see: <a href="https://github.com/oracle-quickstart/oci-kubernetes-monitoring" 
      target="_blank" rel="noopener noreferrer">oci-kubernetes-monitoring</a>
    default: compartment_ocid

  # Option to create Logging Analytics
  opt_create_new_la_logGroup: # change this to create new log group
    type: boolean
    title: Select this check box if you want to create a new log group
    default: false

  # OCI Logging Analytics LogGroup OCID of existing LogGroup
  oci_la_logGroup_id:
    type: oci:logan:loggroup:id
    dependsOn:
      compartmentId: ${oci_onm_compartment_ocid}
    title: OCI Logging Analytics log group
    description: Log groups are logical containers for log data, and they provide access control for your data using IAM policies.
    required: true
    visible:
      not:
        - opt_create_new_la_logGroup

  # New Log Group to collect Kubernetes data
  oci_la_logGroup_name:
    type: string
    maxLength: 255
    minLength: 1
    required: true
    title: Enter OCI Logging Analytics log group name
    description: "Tip: To make the log group easy to find in Dashboards and Logs Explorer pages, provide a unique name associated with your cluster name."
    visible:
      and:
        - opt_create_new_la_logGroup
    pattern: '^([a-zA-Z0-9]|[a-zA-Z0-9][\\ a-zA-Z0-9_\-]*[\\a-zA-Z\-0-9_])$'  

  # Option to enable/disable metric server installation during helm deployment
  opt_create_new_la_entity:
    type: boolean
    title:  Select this check box if you want to create a new Kubernetes Cluster Entity for this cluster
    description: Clear this check box if you want to use an existing Logging Analytics Entity
    default: true
    visible: ${show_advanced_options}

  # OKE Cluster OCID
  oke_cluster_entity_ocid:
    type: string
    title: "Enter OCI Logging Analytics kubernetes cluster Entity OCID"
    description: "Note: This must be a valid Logging Analytics Entity of type - \"Kubernetes Cluster\"."
    required: true #TODO does this need to be required?
    pattern: "^ocid1\\.(loganalyticsentity)\\.\\S+$"
    # maxLength: 93 # Don't set as realm ID is part of OCID
    minLength: 93 # mz char count in private endpoint ocid
    visible:
      and:
        - ${show_advanced_options}
        - not: 
          - ${opt_create_new_la_entity}

  # Option to create Dynamic Group and Policies
  opt_import_dashboards:
    type: boolean
    title: Select this check box to import dashboards
    description: "Note: You may need to manually clean up the dashboards when you destroy the stack as dashboards will not be deleted automatically."
    default: true
    required: true
    visible:
      and:
        - ${show_advanced_options}

  # OCI tags
  tags:
    type: oci:identity:tag:value
    title: "Tags"
    required: false
    dependsOn:
      compartmentId: ${tenancy_ocid} #TODO check if this needs to be tenancy or onm compartment instead

  ####
  ##  Helm chart Configuration
  ####

  helm_chart_version:
    type: string
    maxLength: 15
    # minLength: 5 # setting minimum length makes this option mandatory regardless of required: false property
    default: "null"
    title: Enter oci-onm helm chart version
    description: |-
      Ex: 3.3.0 | For list of previous releases see: <a href="https://github.com/oracle-quickstart/oci-kubernetes-monitoring/releases" 
      target="_blank" rel="noopener noreferrer">https://github.com/oracle-quickstart/oci-kubernetes-monitoring/releases</a>
    required: false
    # ref - https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
    pattern: '(^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$|^null$)'


  # Option to enable/disable metric server installation during helm deployment
  opt_deploy_metric_server:
    type: boolean
    title: Enable Metric Server installation
    description: Clear this check box if Metric Server is already installed in your cluster.
    default: true

  # Fluentd Base Directory
  fluentd_baseDir_path:
    type: string
    maxLength: 255
    minLength: 1
    title: FluentD working directory
    description: A directory on the node (with read & write permission) to use for storing data related to Fluentd.
    default: /var/log
    required: true
    pattern: '^/[\w- /]*$'

  # Option to enable/disable metric server installation during helm deployment
  opt_skip_helm_chart:
    type: boolean
    title: Skip helm chart installation
    description: |- 
      Select this check box to SKIP helm chart installation.
      [★] Note: Stack generates <a href="https://helm.sh/docs/intro/using_helm/" target="_blank" rel="noopener noreferrer">helm cli</a> 
      commands for manual helm chart installation.
    default: false

  # kubernetes_namespace:
  #   type: string
  #   minLength: 1
  #   maxLength: 63
  #   title: Kubernetes Namespace
  #   description: Kubernetes Namespace in which the monitoring solution to be deployed
  #   default: kube-system
  #   pattern: '^([a-z0-9]|[a-z][a-z\-0-9]*[a-z0-9])$' #Ref - https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
  #   required: true