# By default, a cluster role, cluster role binding and serviceaccount will be created for the monitoring pods to be able to (readonly) access various objects within the cluster, to support collection of various telemetry data. You may set this to false and provide your own serviceaccount (in the parent chart(s)) which has the necessary cluster role(s) binded to it. Refer, README for the cluster role definition and other details.
createServiceAccount: true
# If createNamespace is set to true, it tries to create the namespace defined in 'namespace' variable.
createNamespace: true
# Kubernetes Namespace in which the serviceaccount to be created.
namespace: oci-onm
# Prefix to be attached to resources created through this chart. Not all resources may have this prefix.
resourceNamePrefix: oci-onm
