{{- if eq (include "common.createServiceAccount" .) "true" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.serviceAccount" . }}
  namespace: {{ include "common.namespace" . }}
{{- end }}
