# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "logan.resourceNamePrefix" . }}-discovery
  namespace: {{ include "logan.namespace" . }}
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: oci-onm
          containers:
          - name: k8-discovery-job
            image: iad.ocir.io/id3m3bqjn6oc/k8-objects-discovery:commit-f397 
            env:
            - name: K8_CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: k8-discovery-config
                  key: k8_cluster_name
            - name: K8_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: k8-discovery-config
                  key: k8_cluster_id
            - name: OCI_LA_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: k8-discovery-config
                  key: oci_la_namespace
            - name: OCI_LA_LOG_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: k8-discovery-config
                  key: oci_la_log_group_id
            volumeMounts:
            - name: ociconfigdir
              mountPath: /var/opt/.oci
              readOnly: true      
            command:
                - oci-logan-oke-resources-discovery
                - --kubernetes_cluster_name
                - $(K8_CLUSTER_NAME)
                - --kubernetes_cluster_id
                - $(K8_CLUSTER_ID)
                - --oci_la_namespace
                - $(OCI_LA_NAMESPACE)
                - --oci_la_log_group_id
                - $(OCI_LA_LOG_GROUP_ID)
          volumes:
          - name: ociconfigdir
            projected:
              sources:
              - secret:
                  name: oci-onm-oci-config
