{{- $authtype := .Values.authtype | lower }}
{{- $resourceNamePrefix := .Values.global.resourceNamePrefix }}
{{- $kubernetesClusterName := (include "logan.kubernetesClusterName" .) }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.global.resourceNamePrefix }}-discovery
  namespace: {{ include "logan.namespace" . }}
spec:
  schedule: {{ .Values.objectDiscovery.cronSchedule | quote }}
  startingDeadlineSeconds: 100
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ include "logan.serviceAccount" . }}
          containers:
          - name: k8-discovery-job
            image: {{ .Values.image.url }}
            {{- if eq $authtype "config" }}
            volumeMounts:
            - name: ociconfigdir
              mountPath: {{ .Values.oci.path }}
              readOnly: true
            {{- end }}
            command:
              # object discovery script
              - oci-logan-oke-resources-discovery
              # mandatory params
              - --kubernetes_cluster_name
              {{- if ne $kubernetesClusterName "UNDEFINED" }}
              - {{ $kubernetesClusterName }}
              {{- else }}
              {{ required "kubernetes_cluster_name is required" .Values.global.kubernetesClusterName }}
              {{- end }}
              - --oci_la_namespace
              {{- if .Values.objectDiscovery.cmdInputs.oci_la_namespace }}
              - {{ .Values.objectDiscovery.cmdInputs.oci_la_namespace }}
              {{- else if .Values.ociLANamespace }}
              - {{ .Values.ociLANamespace }}
              {{- else }}
              {{ required "ociLANamespace is required" .Values.ociLANamespace }}
              {{- end }}
              - --oci_la_log_group_id
              {{- if .Values.objectDiscovery.cmdInputs.oci_la_log_group_id }}
              - {{ .Values.objectDiscovery.cmdInputs.oci_la_log_group_id }}
              {{- else if .Values.ociLALogGroupID }}
              - {{ .Values.ociLALogGroupID }}
              {{- else }}
              {{ required "ociLALogGroupID is required" .Values.ociLALogGroupID }}
              {{- end }}
              # optional params
              {{- if .Values.ociLAEndpoint }}
              - --endpoint
              - {{ .Values.ociLAEndpoint }}
              {{- end }}
              {{- if .Values.ociLAClusterEntityID }}
              - --kubernetes_cluster_entity_id
              - {{ .Values.ociLAClusterEntityID  }}
              {{- end }}
              # params required when authtype is set as config
              {{- if eq .Values.authtype "config" }}
              {{- if and .Values.oci.path .Values.oci.file }}
              - --config_file_location
              - {{ .Values.oci.path -}}/{{ .Values.oci.file }}
              {{- else }}
              {{- required "missing config file. {{ .Values.oci.path -}}/{{ .Values.oci.file }}" .Values.oci.path }}
              {{- end }}
              {{- if .Values.objectDiscovery.cmdInputs.profile_name }}
              - --profile_name
              - {{ .Values.objectDiscovery.cmdInputs.profile_name }}
              {{- end }}
              {{- end }}
              {{- if .Values.objectDiscovery.cmdInputs.kube_config_location }}
              - --kube_config_location
              - {{ .Values.objectDiscovery.cmdInputs.kube_config_location }}
              {{- end }}
              {{- if .Values.objectDiscovery.cmdInputs.kubernetes_url }}
              - --kubernetes_url
              - {{ .Values.objectDiscovery.cmdInputs.kubernetes_url }}
              {{- end }}
              {{- if .Values.objectDiscovery.cmdInputs.client_cert }}
              - --client_cert
              - {{ .Values.objectDiscovery.cmdInputs.client_cert }}
              {{- end }}                
              {{- if .Values.objectDiscovery.cmdInputs.client_key }}
              - --client_key
              - {{ .Values.objectDiscovery.cmdInputs.client_key }}
              {{- end }}
              {{- if .Values.objectDiscovery.cmdInputs.ca_file }}
              - --ca_file
              - {{ .Values.objectDiscovery.cmdInputs.ca_file }}
              {{- end }}
              {{- if .Values.objectDiscovery.cmdInputs.verify_ssl }}
              - --verify_ssl
              - {{ .Values.objectDiscovery.cmdInputs.verify_ssl }}
              {{- end }}
              {{- if .Values.objectDiscovery.cmdInputs.bearer_token_file }}
              - --bearer_token_file
              - {{ .Values.objectDiscovery.cmdInputs.bearer_token_file }}
              {{- end }}                
              {{- if .Values.objectDiscovery.cmdInputs.secret_dir }}
              - --secret_dir
              - {{ .Values.objectDiscovery.cmdInputs.secret_dir }}
              {{- end }}
              {{- if .Values.objectDiscovery.cmdInputs.discovery }}
              - --discovery
              - {{ .Values.objectDiscovery.cmdInputs.discovery }}
              {{- end }}
              {{- if index .Values.objectDiscovery.cmdInputs "skip-upload" }}
              - --skip-upload
              {{- end }}
              {{- if .Values.objectDiscovery.cmdInputs.log_format }}
              - --log_format
              - {{ .Values.objectDiscovery.cmdInputs.log_format }}
              {{- end }}                
              {{- if .Values.objectDiscovery.cmdInputs.log_level }}
              - --log_level
              - {{ .Values.objectDiscovery.cmdInputs.log_level }}
              {{- end }}
              {{- if .Values.objectDiscovery.cmdInputs.enable_threading }}
              - --enable_threading
              {{- end }}
              {{- if .Values.objectDiscovery.cmdInputs.thread_count }}
              - --thread_count
              - {{ .Values.objectDiscovery.cmdInputs.thread_count }}
              {{- end }}
          {{- if eq $authtype "config" }}
          volumes:
          - name: ociconfigdir
            projected:
              sources:
              - secret:
                  name: {{ $resourceNamePrefix }}-oci-config
          {{- end }}