{{- $authtype := .Values.authtype | lower }}
{{- if eq $authtype "config" }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "logan.resourceNamePrefix" . }}-credentials-secret
  namespace: {{ include "logan.namespace" . }}
stringData:
  {{- range $key, $value := .Values.oci.configFiles }}
  {{ $key }}: |
    {{- include "common.tplvalues.render" (dict "value" $value "context" $) | nindent 4 }}
  {{- end }}
{{- end}}
