apiVersion: v1
kind: ConfigMap
metadata:
  name: mgmtagent-monitoring-config
  namespace: {{ default "mgmtagent" .Values.namespace }}
data:
  monitoring.properties: |
    # compartmentId to push Monitoring metrics
    compartmentId={{ .Values.kubernetesCluster.compartmentId }}
    # Kubernetes cluster name
    clusterName={{ .Values.kubernetesCluster.name }}
    # Kubernetes Namespace to monitor
    kubernetesNamespace={{ .Values.kubernetesCluster.namespace }}