apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mgmt-agent.resourceNamePrefix" . }}-metrics
  namespace: {{ include "mgmt-agent.namespace" . }}
data:
  monitoring.properties: |
    # compartmentId to push Monitoring metrics
    compartmentId={{ .Values.kubernetesCluster.compartmentId }}
    # Kubernetes cluster name
    clusterName={{ include "mgmt-agent.kubernetesClusterName" . }}
    # Kubernetes Namespace to monitor
    kubernetesNamespace={{ .Values.kubernetesCluster.namespace }}
