# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent
  namespace: {{ include "mgmt-agent.namespace" . }}
  labels:
    app: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent
spec:
  serviceName: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent
  template:
    metadata:
      labels:
        app: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent
    spec:
      serviceAccountName: {{ include "mgmt-agent.serviceAccount" . }}
      imagePullSecrets:
        - name: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent-container-registry-key
      restartPolicy: Always
      containers:
        - name: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent
          image: {{ .Values.mgmtagent.image.url }}
          volumeMounts:
            - name: mgmtagent-secret
              mountPath: /opt/oracle/mgmtagent_secret
              readOnly: true
            - name: mgmtagent-pvc
              mountPath: /opt/oracle
            - name: mgmtagent-config
              mountPath: /opt/oracle/mgmtagent_config
      volumes:
        - name: mgmtagent-secret
          secret:
            secretName: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent-rsp
        - name: mgmtagent-config
          configMap:
            name: {{ include "mgmt-agent.resourceNamePrefix" . }}-metrics
  volumeClaimTemplates:
    - metadata:
        name: mgmtagent-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "oci-bv"
        resources:
          requests:
            storage: 2Gi
