apiVersion: v1
kind: Service
metadata:
  name: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent
  namespace: {{ include "mgmt-agent.namespace" . }}
  labels:
    app: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent
spec:
  clusterIP: None
  selector:
    app: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent
